server:
  port: 8060
  forward-headers-strategy: framework
custom:
  message: hello-from-github1

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/

logging:
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss}){blue} %clr([%X{traceId:-},%X{spanId:-}]){cyan} %clr(${LOG_LEVEL_PATTERN:-%5p}) %m%n"

spring:
  output:
    ansi:
      enabled: always
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: employee-service
              uri: lb://employee-service
              predicates:
                - Path=/employee/**
              filters:
                - RewritePath=/employee/(?<path>.*), /${path}
            - id: department-service
              uri: lb://department-service
              predicates:
                - Path=/department/**
              filters:
                - RewritePath=/department/(?<path>.*), /${path}
            - id: organization-service
              uri: lb://organization-service
              predicates:
                - Path=/organization/**
              filters:
                - RewritePath=/organization/(?<path>.*), /${path}
            - id: employee-openapi
              uri: lb://employee-service
              predicates:
                - Path=/v3/api-docs/employee
              filters:
                - RewritePath=/v3/api-docs/employee, /v3/api-docs
            - id: department-openapi
              uri: lb://department-service
              predicates:
                - Path=/v3/api-docs/department
              filters:
                - RewritePath=/v3/api-docs/department, /v3/api-docs
            - id: organization-openapi
              uri: lb://organization-service
              predicates:
                - Path=/v3/api-docs/organization
              filters:
                - RewritePath=/v3/api-docs/organization, /v3/api-docs

springdoc:
  swagger-ui:
    use-root-path: true
    urls:
      - name: employee
        url: /v3/api-docs/employee
      - name: department
        url: /v3/api-docs/department
      - name: organization
        url: /v3/api-docs/organization
  api-docs:
    version: openapi_3_1
  cache:
    disabled: true

management:
  tracing:
    sampling:
      probability: 1.0
